# Well, take a guess what this notebook is for

This noteboook we will use to COMPARE the results we got from V2 and V3 and see how different or close or howEVER the results are

We will focus on things like,
- Whether the picks changed
- Did the average finish improve or not
- How are the predictions from chaotic races
- And most importantly, did the fantasy logic become *smarter*

In [41]:
import pandas as pd

In [42]:
v2 = pd.read_csv("../results/fantasy_v2_results.csv")
v3 = pd.read_csv("../results/fantasy_v3_results.csv")

# print(v2.columns)
# print(v3.columns)

In [43]:
v2[["RaceName", "Average Actual Finish", "Average Prediction Error"]].head()

                    RaceName  Average Actual Finish  Average Prediction Error
0        Japanese Grand Prix                   3.50                      1.01
1         Chinese Grand Prix                   6.33                      1.86
2  Emilia Romagna Grand Prix                   4.50                      0.88
3   Saudi Arabian Grand Prix                   4.60                      0.46
4           Miami Grand Prix                   5.33                      1.21

In [44]:
v3[["RaceName", "Average Actual Finish", "Average Prediction Error"]].head()

                    RaceName  Average Actual Finish  Average Prediction Error
0        Japanese Grand Prix                   4.17                      0.69
1         Chinese Grand Prix                   6.33                      1.86
2  Emilia Romagna Grand Prix                   4.50                      0.88
3   Saudi Arabian Grand Prix                   4.60                      0.46
4           Miami Grand Prix                   5.33                      1.21

In [45]:
comparison = pd.DataFrame({
    "RaceName": v2["RaceName"],

    "V2 Average Finish": v2["Average Actual Finish"],
    "V3 Average Finish": v3["Average Actual Finish"],

    "V2 Top5": v2["Top 5 hit rate"],
    "V3 Top5": v3["Top 5 hit rate"],

    "V2 Top10": v2["Top 10 hit rate"],
    "V3 Top10": v3["Top 10 hit rate"],

    "V2 Picks": v2["Picks"],
    "V3 Picks": v3["Picks"]  
})

comparison

,RaceName,V2 Average Finish,V3 Average Finish,V2 Top5,V3 Top5,V2 Top10,V3 Top10,V2 Picks,V3 Picks
0,Japanese Grand Prix,3.50,4.17,0.83,0.67,1.00,1.00,"VER, PER, NOR, LEC, ALO, SAI","VER, PER, NOR, LEC, RUS, ALO"
1,Chinese Grand Prix,6.33,6.33,0.50,0.50,0.83,0.83,"VER, PER, LEC, RUS, HAM, STR","VER, PER, LEC, HAM, RUS, STR"
2,Emilia Romagna Grand Prix,4.50,4.50,0.50,0.50,1.00,1.00,"VER, NOR, LEC, HAM, PER, RUS","VER, NOR, LEC, PER, HAM, RUS"
3,Saudi Arabian Grand Prix,4.60,4.60,0.60,0.60,1.00,1.00,"VER, LEC, PIA, RUS, HAM","VER, LEC, PIA, RUS, HAM"
4,Miami Grand Prix,5.33,5.33,0.50,0.50,1.00,1.00,"VER, PER, LEC, HAM, RUS, ALO","VER, PER, LEC, ALO, HAM, RUS"
5,Spanish Grand Prix,4.33,4.33,0.67,0.67,1.00,1.00,"VER, NOR, HAM, PER, PIA, LEC","VER, NOR, HAM, PER, PIA, LEC"
6,United States Grand Prix,5.33,5.33,0.50,0.50,0.83,0.83,"VER, NOR, LEC, RUS, PER, MAG","VER, NOR, LEC, RUS, PER, MAG"
7,Austrian Grand Prix,4.00,4.00,0.67,0.67,1.00,1.00,"VER, RUS, SAI, HUL, PIA, PER","VER, RUS, SAI, PIA, HUL, PER"
8,Dutch Grand Prix,4.33,4.33,0.67,0.67,1.00,1.00,"VER, NOR, PIA, HAM, SAI, PER","VER, NOR, PIA, HAM, SAI, PER"
9,Singapore Grand Prix,3.83,3.83,0.67,0.67,1.00,1.00,"VER, NOR, PIA, SAI, HAM, RUS","VER, NOR, PIA, SAI, HAM, RUS"
10,Mexico City Grand Prix,4.00,4.00,0.67,0.67,1.00,1.00,"VER, SAI, NOR, PIA, HAM, LEC","VER, SAI, NOR, PIA, HAM, LEC"
11,Hungarian Grand Prix,4.33,4.33,0.67,0.67,1.00,1.00,"NOR, PIA, VER, PER, RUS, HAM","NOR, PIA, VER, PER, RUS, HAM"
12,Monaco Grand Prix,3.80,3.80,0.80,0.80,1.00,1.00,"LEC, NOR, PIA, HAM, RUS","LEC, NOR, PIA, HAM, RUS"
13,Canadian Grand Prix,3.50,4.17,0.83,0.67,1.00,1.00,"VER, NOR, RUS, HAM, ALO, PIA","VER, NOR, RUS, HAM, GAS, ALO"
14,Azerbaijan Grand Prix,7.00,7.00,0.50,0.50,0.67,0.67,"PIA, LEC, VER, HAM, GAS, RIC","PIA, LEC, VER, HAM, GAS, RIC"
15,Qatar Grand Prix,5.33,5.67,0.67,0.67,0.83,0.83,"VER, RUS, LEC, GAS, ZHO, HAM","VER, RUS, LEC, GAS, LAW, ZHO"
16,Belgian Grand Prix,6.50,6.50,0.50,0.50,0.67,0.67,"HAM, LEC, VER, MAG, SAI, STR","HAM, LEC, VER, MAG, STR, SAI"
17,British Grand Prix,4.17,4.17,0.67,0.67,1.00,1.00,"VER, NOR, HAM, PIA, ALO, STR","VER, NOR, HAM, ALO, PIA, STR"
18,Australian Grand Prix,3.60,3.60,0.80,0.80,1.00,1.00,"SAI, LEC, NOR, PIA, ALO","SAI, LEC, NOR, ALO, PIA"
19,Italian Grand Prix,4.83,4.83,0.50,0.50,1.00,1.00,"NOR, PIA, LEC, VER, MAG, RUS","NOR, PIA, LEC, VER, MAG, RUS"
20,Las Vegas Grand Prix,3.67,4.17,0.83,0.83,1.00,1.00,"SAI, RUS, LEC, HAM, VER, PIA","SAI, RUS, LEC, HAM, PER, VER"
21,Abu Dhabi Grand Prix,5.67,5.67,0.50,0.50,1.00,1.00,"SAI, GAS, RUS, LEC, ALO, HUL","SAI, GAS, RUS, LEC, ALO, HUL"
22,São Paulo Grand Prix,4.50,4.50,0.67,0.67,1.00,1.00,"NOR, LEC, RUS, VER, GAS, PIA","NOR, LEC, RUS, VER, GAS, PIA"

In [46]:
comparison["Finish difference"] = (
    comparison["V3 Average Finish"] - 
    comparison["V2 Average Finish"]
)

comparison["Top 5 Difference"] = (
    comparison["V3 Top5"] - 
    comparison["V2 Top5"]
)

comparison["Top 10 Difference"] = (
    comparison["V3 Top10"] - 
    comparison["V2 Top10"]
)

comparison["Changed Picks"] = (
    comparison["V3 Picks"] != comparison["V2 Picks"]
)

comparison

# Results not bad, personally I do not like the decimals so im gonna change it up

,RaceName,V2 Average Finish,V3 Average Finish,V2 Top5,V3 Top5,V2 Top10,V3 Top10,V2 Picks,V3 Picks,Finish difference,Top 5 Difference,Top 10 Difference,Changed Picks
0,Japanese Grand Prix,3.50,4.17,0.83,0.67,1.00,1.00,"VER, PER, NOR, LEC, ALO, SAI","VER, PER, NOR, LEC, RUS, ALO",0.67,-0.16,0.0,True
1,Chinese Grand Prix,6.33,6.33,0.50,0.50,0.83,0.83,"VER, PER, LEC, RUS, HAM, STR","VER, PER, LEC, HAM, RUS, STR",0.00,0.00,0.0,True
2,Emilia Romagna Grand Prix,4.50,4.50,0.50,0.50,1.00,1.00,"VER, NOR, LEC, HAM, PER, RUS","VER, NOR, LEC, PER, HAM, RUS",0.00,0.00,0.0,True
3,Saudi Arabian Grand Prix,4.60,4.60,0.60,0.60,1.00,1.00,"VER, LEC, PIA, RUS, HAM","VER, LEC, PIA, RUS, HAM",0.00,0.00,0.0,False
4,Miami Grand Prix,5.33,5.33,0.50,0.50,1.00,1.00,"VER, PER, LEC, HAM, RUS, ALO","VER, PER, LEC, ALO, HAM, RUS",0.00,0.00,0.0,True
5,Spanish Grand Prix,4.33,4.33,0.67,0.67,1.00,1.00,"VER, NOR, HAM, PER, PIA, LEC","VER, NOR, HAM, PER, PIA, LEC",0.00,0.00,0.0,False
6,United States Grand Prix,5.33,5.33,0.50,0.50,0.83,0.83,"VER, NOR, LEC, RUS, PER, MAG","VER, NOR, LEC, RUS, PER, MAG",0.00,0.00,0.0,False
7,Austrian Grand Prix,4.00,4.00,0.67,0.67,1.00,1.00,"VER, RUS, SAI, HUL, PIA, PER","VER, RUS, SAI, PIA, HUL, PER",0.00,0.00,0.0,True
8,Dutch Grand Prix,4.33,4.33,0.67,0.67,1.00,1.00,"VER, NOR, PIA, HAM, SAI, PER","VER, NOR, PIA, HAM, SAI, PER",0.00,0.00,0.0,False
9,Singapore Grand Prix,3.83,3.83,0.67,0.67,1.00,1.00,"VER, NOR, PIA, SAI, HAM, RUS","VER, NOR, PIA, SAI, HAM, RUS",0.00,0.00,0.0,False
10,Mexico City Grand Prix,4.00,4.00,0.67,0.67,1.00,1.00,"VER, SAI, NOR, PIA, HAM, LEC","VER, SAI, NOR, PIA, HAM, LEC",0.00,0.00,0.0,False
11,Hungarian Grand Prix,4.33,4.33,0.67,0.67,1.00,1.00,"NOR, PIA, VER, PER, RUS, HAM","NOR, PIA, VER, PER, RUS, HAM",0.00,0.00,0.0,False
12,Monaco Grand Prix,3.80,3.80,0.80,0.80,1.00,1.00,"LEC, NOR, PIA, HAM, RUS","LEC, NOR, PIA, HAM, RUS",0.00,0.00,0.0,False
13,Canadian Grand Prix,3.50,4.17,0.83,0.67,1.00,1.00,"VER, NOR, RUS, HAM, ALO, PIA","VER, NOR, RUS, HAM, GAS, ALO",0.67,-0.16,0.0,True
14,Azerbaijan Grand Prix,7.00,7.00,0.50,0.50,0.67,0.67,"PIA, LEC, VER, HAM, GAS, RIC","PIA, LEC, VER, HAM, GAS, RIC",0.00,0.00,0.0,False
15,Qatar Grand Prix,5.33,5.67,0.67,0.67,0.83,0.83,"VER, RUS, LEC, GAS, ZHO, HAM","VER, RUS, LEC, GAS, LAW, ZHO",0.34,0.00,0.0,True
16,Belgian Grand Prix,6.50,6.50,0.50,0.50,0.67,0.67,"HAM, LEC, VER, MAG, SAI, STR","HAM, LEC, VER, MAG, STR, SAI",0.00,0.00,0.0,True
17,British Grand Prix,4.17,4.17,0.67,0.67,1.00,1.00,"VER, NOR, HAM, PIA, ALO, STR","VER, NOR, HAM, ALO, PIA, STR",0.00,0.00,0.0,True
18,Australian Grand Prix,3.60,3.60,0.80,0.80,1.00,1.00,"SAI, LEC, NOR, PIA, ALO","SAI, LEC, NOR, ALO, PIA",0.00,0.00,0.0,True
19,Italian Grand Prix,4.83,4.83,0.50,0.50,1.00,1.00,"NOR, PIA, LEC, VER, MAG, RUS","NOR, PIA, LEC, VER, MAG, RUS",0.00,0.00,0.0,False
20,Las Vegas Grand Prix,3.67,4.17,0.83,0.83,1.00,1.00,"SAI, RUS, LEC, HAM, VER, PIA","SAI, RUS, LEC, HAM, PER, VER",0.50,0.00,0.0,True
21,Abu Dhabi Grand Prix,5.67,5.67,0.50,0.50,1.00,1.00,"SAI, GAS, RUS, LEC, ALO, HUL","SAI, GAS, RUS, LEC, ALO, HUL",0.00,0.00,0.0,False
22,São Paulo Grand Prix,4.50,4.50,0.67,0.67,1.00,1.00,"NOR, LEC, RUS, VER, GAS, PIA","NOR, LEC, RUS, VER, GAS, PIA",0.00,0.00,0.0,False

In [47]:
# print(comparison.round(3).head())

In [48]:
def driver_pick_changes(v2_picks, v3_picks):
    v2_list = [pick.strip() for pick in v2_picks.split(",")]
    v3_list = [pick.strip() for pick in v3_picks.split(",")]


    v2_set = set(v2_list)
    v3_set = set(v3_list)

    removed = sorted(v2_set - v3_set)
    added = sorted(v3_set - v2_set)

    if removed or added:
        return f"Removed {', '.join(removed)} | Added: {', '.join(added)}"
    
    if v2_list != v3_list:
        return "Same drivers, different order"
    
    return "False"

# This function is by far the most useful one here, so we know the results will fluctuate a bit and because it is hard to read side by side
# This function will basically use the set function to check if the values picked are same or not
# Set makes our life easy #set(s)4life
# Some rows have same drivers but different order while others have no change
# But the ones with changes we will say who we removed and who we replaced them with

In [49]:
comparison["Pick Changes"] = comparison.apply(
    lambda row: driver_pick_changes(row["V2 Picks"], row["V3 Picks"]),
    axis = 1
)

comparison = comparison.round(3)

comparison

,RaceName,V2 Average Finish,V3 Average Finish,V2 Top5,V3 Top5,V2 Top10,V3 Top10,V2 Picks,V3 Picks,Finish difference,Top 5 Difference,Top 10 Difference,Changed Picks,Pick Changes
0,Japanese Grand Prix,3.50,4.17,0.83,0.67,1.00,1.00,"VER, PER, NOR, LEC, ALO, SAI","VER, PER, NOR, LEC, RUS, ALO",0.67,-0.16,0.0,True,Removed SAI | Added: RUS
1,Chinese Grand Prix,6.33,6.33,0.50,0.50,0.83,0.83,"VER, PER, LEC, RUS, HAM, STR","VER, PER, LEC, HAM, RUS, STR",0.00,0.00,0.0,True,"Same drivers, different order"
2,Emilia Romagna Grand Prix,4.50,4.50,0.50,0.50,1.00,1.00,"VER, NOR, LEC, HAM, PER, RUS","VER, NOR, LEC, PER, HAM, RUS",0.00,0.00,0.0,True,"Same drivers, different order"
3,Saudi Arabian Grand Prix,4.60,4.60,0.60,0.60,1.00,1.00,"VER, LEC, PIA, RUS, HAM","VER, LEC, PIA, RUS, HAM",0.00,0.00,0.0,False,False
4,Miami Grand Prix,5.33,5.33,0.50,0.50,1.00,1.00,"VER, PER, LEC, HAM, RUS, ALO","VER, PER, LEC, ALO, HAM, RUS",0.00,0.00,0.0,True,"Same drivers, different order"
5,Spanish Grand Prix,4.33,4.33,0.67,0.67,1.00,1.00,"VER, NOR, HAM, PER, PIA, LEC","VER, NOR, HAM, PER, PIA, LEC",0.00,0.00,0.0,False,False
6,United States Grand Prix,5.33,5.33,0.50,0.50,0.83,0.83,"VER, NOR, LEC, RUS, PER, MAG","VER, NOR, LEC, RUS, PER, MAG",0.00,0.00,0.0,False,False
7,Austrian Grand Prix,4.00,4.00,0.67,0.67,1.00,1.00,"VER, RUS, SAI, HUL, PIA, PER","VER, RUS, SAI, PIA, HUL, PER",0.00,0.00,0.0,True,"Same drivers, different order"
8,Dutch Grand Prix,4.33,4.33,0.67,0.67,1.00,1.00,"VER, NOR, PIA, HAM, SAI, PER","VER, NOR, PIA, HAM, SAI, PER",0.00,0.00,0.0,False,False
9,Singapore Grand Prix,3.83,3.83,0.67,0.67,1.00,1.00,"VER, NOR, PIA, SAI, HAM, RUS","VER, NOR, PIA, SAI, HAM, RUS",0.00,0.00,0.0,False,False
10,Mexico City Grand Prix,4.00,4.00,0.67,0.67,1.00,1.00,"VER, SAI, NOR, PIA, HAM, LEC","VER, SAI, NOR, PIA, HAM, LEC",0.00,0.00,0.0,False,False
11,Hungarian Grand Prix,4.33,4.33,0.67,0.67,1.00,1.00,"NOR, PIA, VER, PER, RUS, HAM","NOR, PIA, VER, PER, RUS, HAM",0.00,0.00,0.0,False,False
12,Monaco Grand Prix,3.80,3.80,0.80,0.80,1.00,1.00,"LEC, NOR, PIA, HAM, RUS","LEC, NOR, PIA, HAM, RUS",0.00,0.00,0.0,False,False
13,Canadian Grand Prix,3.50,4.17,0.83,0.67,1.00,1.00,"VER, NOR, RUS, HAM, ALO, PIA","VER, NOR, RUS, HAM, GAS, ALO",0.67,-0.16,0.0,True,Removed PIA | Added: GAS
14,Azerbaijan Grand Prix,7.00,7.00,0.50,0.50,0.67,0.67,"PIA, LEC, VER, HAM, GAS, RIC","PIA, LEC, VER, HAM, GAS, RIC",0.00,0.00,0.0,False,False
15,Qatar Grand Prix,5.33,5.67,0.67,0.67,0.83,0.83,"VER, RUS, LEC, GAS, ZHO, HAM","VER, RUS, LEC, GAS, LAW, ZHO",0.34,0.00,0.0,True,Removed HAM | Added: LAW
16,Belgian Grand Prix,6.50,6.50,0.50,0.50,0.67,0.67,"HAM, LEC, VER, MAG, SAI, STR","HAM, LEC, VER, MAG, STR, SAI",0.00,0.00,0.0,True,"Same drivers, different order"
17,British Grand Prix,4.17,4.17,0.67,0.67,1.00,1.00,"VER, NOR, HAM, PIA, ALO, STR","VER, NOR, HAM, ALO, PIA, STR",0.00,0.00,0.0,True,"Same drivers, different order"
18,Australian Grand Prix,3.60,3.60,0.80,0.80,1.00,1.00,"SAI, LEC, NOR, PIA, ALO","SAI, LEC, NOR, ALO, PIA",0.00,0.00,0.0,True,"Same drivers, different order"
19,Italian Grand Prix,4.83,4.83,0.50,0.50,1.00,1.00,"NOR, PIA, LEC, VER, MAG, RUS","NOR, PIA, LEC, VER, MAG, RUS",0.00,0.00,0.0,False,False
20,Las Vegas Grand Prix,3.67,4.17,0.83,0.83,1.00,1.00,"SAI, RUS, LEC, HAM, VER, PIA","SAI, RUS, LEC, HAM, PER, VER",0.50,0.00,0.0,True,Removed PIA | Added: PER
21,Abu Dhabi Grand Prix,5.67,5.67,0.50,0.50,1.00,1.00,"SAI, GAS, RUS, LEC, ALO, HUL","SAI, GAS, RUS, LEC, ALO, HUL",0.00,0.00,0.0,False,False
22,São Paulo Grand Prix,4.50,4.50,0.67,0.67,1.00,1.00,"NOR, LEC, RUS, VER, GAS, PIA","NOR, LEC, RUS, VER, GAS, PIA",0.00,0.00,0.0,False,False

Improved the overall readability of the table and the changed picks and everything

False is the same as same driver, different order because we have no change and its just simply the same thing. 
Since we can see only 3 out of 22 being changed, this means that the overall foundation of this model is not destroyed nor is GridGap a dominating feature which changes the whole model entirely.

In [50]:
comparison["Pick Changes"].value_counts

<bound method IndexOpsMixin.value_counts of 0          Removed SAI | Added: RUS
1     Same drivers, different order
2     Same drivers, different order
3                             False
4     Same drivers, different order
5                             False
6                             False
7     Same drivers, different order
8                             False
9                             False
10                            False
11                            False
12                            False
13         Removed PIA | Added: GAS
14                            False
15         Removed HAM | Added: LAW
16    Same drivers, different order
17    Same drivers, different order
18    Same drivers, different order
19                            False
20         Removed PIA | Added: PER
21                            False
22                            False
Name: Pick Changes, dtype: object>

In [ ]:
comparison[["Finish difference", "Top 5 Difference", "Top 10 Difference"]].describe()
# So basically in the finish difference, overall the v3 model has a +0.095 improvement while had a VERY SMALL slightly off prediction for Top 5 difference
# However, the minimum is there in top 5 difference being -0.16 which means the model kinda got better
# But overall, the model did not change and still works well even with the GridGap

       Finish difference  Top 5 Difference  Top 10 Difference
count          23.000000         23.000000               23.0
mean            0.094783         -0.013913                0.0
std             0.219169          0.046097                0.0
min             0.000000         -0.160000                0.0
25%             0.000000          0.000000                0.0
50%             0.000000          0.000000                0.0
75%             0.000000          0.000000                0.0
max             0.670000          0.000000                0.0