### After hours of testing and feature engineering

This model is by far the best one without the rolling 3 average

**Model V1**
- Train: 2023 F1 race data
- Test: 2024 F1 race data
- Model: RandomForestRegressor
- Best MAE so far: ~1.49

In [2]:
# Overall Pipeline

# 1. Load data
# 2. Sort it by driver name and round number
# 3. Create features
# 4. Select the features
# 5. Combine the training with test
# 6. Encode by team name
# 7. Split the test and train back
# 8. Train the model
# 9. See the predictions
# 10. Then we evaluate and see if we need to do new things

In [3]:
import fastf1
import pandas as pd

fastf1.Cache.enable_cache("../data/cache")

In [4]:
schedule_2023 = fastf1.get_event_schedule(2023)

all_races_2023 = []

for _, event in schedule_2023.iterrows():
    try:
        race_name = event["EventName"]

        session = fastf1.get_session(2023, race_name, "R")
        session.load()

        race_results = session.results[[
            "Abbreviation",
            "TeamName",
            "GridPosition",
            "Position",
            "Status"
        ]].copy()

        race_results["RaceName"] = race_name
        race_results["RoundNumber"] = event["RoundNumber"]
        race_results["Year"] = 2023

        all_races_2023.append(race_results)

        print(f"Successfully loaded {race_name}")
    except Exception as e:

        print(f"Error loading {race_name}: {e}")

df_2023 = pd.concat(all_races_2023, ignore_index=True)

events      WARNING 	Correcting user input 'Pre-Season Testing' to 'British Grand Prix'
core           INFO 	Loading data for British Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '44', '81', '63', '11', '14', '23', '16', '55', '2', '77', '27', '18', '24', '22', '21', '10', '20', '31']
core           INFO 	Loading data for Bahrain Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Successfully loaded Pre-Season Testing

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '11', '14', '55', '44', '18', '63', '77', '10', '23', '22', '2', '20', '21', '27', '24', '4', '31', '16', '81']
core           INFO 	Loading data for Saudi Arabian Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Successfully loaded Bahrain Grand Prix

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Driver 11 completed the race distance 00:00.035000 before the recorded end of the session.
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['11', '1', '14', '63', '44', '55', '16', '31', '10', '20', '22', '27', '24', '21', '81', '2', '4', '77', '23', '18']
core           INFO 	Loading data for Australian Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Successfully loaded Saudi Arabian Grand Prix

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '44', '14', '18', '11', '4', '27', '81', '24', '22', '77', '55', '10', '31', '21', '2', '20', '63', '23', '16']
core           INFO 	Loading data for Azerbaijan Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Successfully loaded Australian Grand Prix

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['11', '1', '16', '14', '55', '44', '18', '63', '4', '22', '81', '23', '20', '10', '31', '2', '27', '77', '24', '21']
core           INFO 	Loading data for Miami Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Successfully loaded Azerbaijan Grand Prix

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '11', '14', '63', '55', '44', '16', '10', '31', '20', '22', '18', '77', '23', '27', '24', '4', '21', '81', '2']
core           INFO 	Loading data for Monaco Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Successfully loaded Miami Grand Prix

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '14', '31', '44', '63', '16', '10', '55', '4', '81', '77', '21', '24', '23', '22', '11', '27', '2', '20', '18']
core           INFO 	Loading data for Spanish Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Successfully loaded Monaco Grand Prix

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Driver 1 completed the race distance 00:00.037000 before the recorded end of the session.
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '44', '63', '11', '55', '18', '14', '31', '24', '10', '16', '22', '81', '21', '27', '23', '4', '20', '77', '2']
core           INFO 	Loading data for Canadian Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Successfully loaded Spanish Grand Prix

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Fixed incorrect tyre stint information for driver '22'
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '14', '44', '16', '55', '11', '23', '31', '18', '77', '81', '10', '4', '22', '27', '24', '20', '21', '63', '2']
core           INFO 	Loading data for Austrian Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Successfully loaded Canadian Grand Prix

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '16', '11', '4', '14', '55', '63', '44', '18', '10', '23', '24', '2', '31', '77', '81', '21', '20', '22', '27']
core           INFO 	Loading data for British Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...

Successfully loaded Austrian Grand Prix

req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '44', '81', '63', '11', '14', '23', '16', '55', '2', '77', '27', '18', '24', '22', '21', '10', '20', '31']
core           INFO 	Loading data for Hungarian Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Successfully loaded British Grand Prix

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '11', '44', '81', '63', '16', '55', '14', '18', '23', '77', '3', '27', '22', '24', '20', '2', '31', '10']
core           INFO 	Loading data for Belgian Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Successfully loaded Hungarian Grand Prix

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '11', '16', '44', '14', '63', '4', '31', '18', '22', '10', '77', '24', '23', '20', '3', '2', '27', '55', '81']
core           INFO 	Loading data for Dutch Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Successfully loaded Belgian Grand Prix

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Driver 1 completed the race distance 00:02.059000 before the recorded end of the session.
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '14', '10', '11', '55', '44', '4', '23', '81', '31', '18', '27', '40', '77', '22', '20', '63', '24', '16', '2']
core           INFO 	Loading data for Italian Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Successfully loaded Dutch Grand Prix

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 22)
core        WARNING 	Driver 1 completed the race distance 06:25.888000 before the recorded end of the session.
core        WARNING 	Driver 11 completed the race distance 06:19.824000 before the recorded end of the session.
core        WARNING 	Driver 55 completed the race distance 06:14.695000 before the recorded end of the session.
core        WARNING 	Driver 16 completed the race distance 06:14.511000 before the recorded end of the session.
core        WARNING 	Driver 63 completed the race distance 06:07.860000 before the recorded end of the session.
core        WARNING 	Driver 44 completed the race distance 05:48.209000 before the recorded end of the session.
core        WARNING 	Driver 23 completed the race distance 05:40.782000 before the recorded end of the session.
core        WARNING 	Driver 4 completed the race distance 05:40.439000 before the recorded end of the session.
core        WARNING 	Driver 14 completed the race distance 05:39.594000 before the recorded end of the session.
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '11', '55', '16', '63', '44', '23', '4', '14', '77', '40', '81', '2', '24', '10', '18', '27', '20', '31', '22']
core           INFO 	Loading data for Singapore Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Successfully loaded Italian Grand Prix

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 18)
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['55', '4', '44', '16', '1', '10', '81', '11', '40', '20', '23', '24', '27', '2', '14', '63', '77', '31', '22', '18']
core           INFO 	Loading data for Japanese Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Successfully loaded Singapore Grand Prix

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Driver 1 completed the race distance 00:00.076000 before the recorded end of the session.
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '81', '16', '44', '55', '63', '14', '31', '10', '40', '22', '24', '27', '20', '23', '2', '18', '11', '77']
events      WARNING 	Correcting user input 'Qatar Grand Prix' to 'Qatar Grand Prix'
core           INFO 	Loading data for Qatar Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Successfully loaded Japanese Grand Prix

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 55)
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '81', '4', '63', '16', '14', '31', '77', '24', '11', '18', '10', '23', '20', '22', '27', '40', '2', '44', '55']
events      WARNING 	Correcting user input 'United States Grand Prix' to 'United States Grand Prix'
core           INFO 	Loading data for United States Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Successfully loaded Qatar Grand Prix

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '55', '11', '63', '10', '18', '22', '23', '2', '27', '77', '24', '20', '3', '14', '81', '31', '44', '16']
core           INFO 	Loading data for Mexico City Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Successfully loaded United States Grand Prix

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '44', '16', '55', '4', '63', '3', '81', '23', '31', '10', '22', '27', '24', '77', '2', '18', '14', '20', '11']
core           INFO 	Loading data for São Paulo Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Successfully loaded Mexico City Grand Prix

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 16)
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '14', '11', '18', '55', '10', '44', '22', '31', '2', '27', '3', '81', '63', '77', '24', '20', '23', '16']
core           INFO 	Loading data for Las Vegas Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Successfully loaded São Paulo Grand Prix

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Driver 1 completed the race distance 00:00.001000 before the recorded end of the session.
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '16', '11', '31', '18', '55', '44', '63', '14', '81', '10', '23', '20', '3', '24', '2', '77', '22', '27', '4']
core           INFO 	Loading data for Abu Dhabi Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Successfully loaded Las Vegas Grand Prix

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '16', '63', '11', '4', '81', '14', '22', '44', '18', '3', '31', '10', '23', '27', '2', '24', '55', '77', '20']

Successfully loaded Abu Dhabi Grand Prix

In [5]:
schedule_2024 = fastf1.get_event_schedule(2024)

all_races_2024 = []

for _, event in schedule_2024.iterrows():
    try:
        race_name = event["EventName"]

        session = fastf1.get_session(2024, race_name, "R")
        session.load()

        race_results = session.results[[
            "Abbreviation",
            "TeamName",
            "GridPosition",
            "Position",
            "Status"
        ]].copy()

        race_results["RaceName"] = race_name
        race_results["RoundNumber"] = event["RoundNumber"]
        race_results["Year"] = 2024

        all_races_2024.append(race_results)

        print(f"Successfully loaded {race_name}")
    except Exception as e:

        print(f"Error loading {race_name}: {e}")

df_2024 = pd.concat(all_races_2024, ignore_index=True)

events      WARNING 	Correcting user input 'Pre-Season Testing' to 'Singapore Grand Prix'
core           INFO 	Loading data for Singapore Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['4', '1', '81', '63', '16', '44', '55', '14', '27', '11', '43', '22', '31', '18', '24', '77', '10', '3', '20', '23']
core           INFO 	Loading data for Bahrain Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Successfully loaded Pre-Season Testing

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '11', '55', '16', '63', '4', '44', '81', '14', '18', '24', '20', '3', '22', '23', '27', '31', '10', '77', '2']
core           INFO 	Loading data for Saudi Arabian Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Successfully loaded Bahrain Grand Prix

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '11', '16', '81', '14', '63', '38', '4', '44', '27', '23', '20', '31', '2', '22', '3', '77', '24', '18', '10']
core           INFO 	Loading data for Australian Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Successfully loaded Saudi Arabian Grand Prix

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 19 drivers: ['55', '16', '4', '81', '11', '18', '22', '14', '27', '20', '23', '3', '10', '77', '24', '31', '63', '44', '1']
core           INFO 	Loading data for Japanese Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Successfully loaded Australian Grand Prix

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '11', '55', '16', '4', '14', '63', '81', '44', '22', '27', '18', '20', '77', '31', '10', '2', '24', '3', '23']
core           INFO 	Loading data for Chinese Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Successfully loaded Japanese Grand Prix

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Driver 1 completed the race distance 00:08.313000 before the recorded end of the session.
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '11', '16', '55', '63', '14', '81', '44', '27', '31', '23', '10', '24', '18', '20', '2', '3', '22', '77']
core           INFO 	Loading data for Miami Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Successfully loaded Chinese Grand Prix

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['4', '1', '16', '11', '55', '44', '22', '63', '14', '31', '27', '10', '81', '24', '3', '77', '18', '23', '20', '2']
core           INFO 	Loading data for Emilia Romagna Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Successfully loaded Miami Grand Prix

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '16', '81', '55', '44', '63', '11', '18', '22', '27', '20', '3', '31', '24', '10', '2', '77', '14', '23']
core           INFO 	Loading data for Monaco Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Successfully loaded Emilia Romagna Grand Prix

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['16', '81', '55', '4', '63', '1', '44', '22', '23', '10', '14', '3', '77', '18', '2', '24', '31', '11', '27', '20']
core           INFO 	Loading data for Canadian Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Successfully loaded Monaco Grand Prix

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '63', '44', '81', '14', '18', '3', '10', '31', '27', '20', '77', '22', '24', '55', '23', '11', '16', '2']
core           INFO 	Loading data for Spanish Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Successfully loaded Canadian Grand Prix

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Driver 1 completed the race distance 00:00.015000 before the recorded end of the session.
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '4', '44', '63', '16', '55', '81', '11', '10', '31', '27', '14', '24', '18', '3', '77', '20', '23', '22', '2']
core           INFO 	Loading data for Austrian Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Successfully loaded Spanish Grand Prix

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['63', '81', '55', '44', '1', '27', '11', '20', '3', '10', '16', '31', '18', '22', '23', '77', '24', '14', '2', '4']
core           INFO 	Loading data for British Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Successfully loaded Austrian Grand Prix

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 10)
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['44', '1', '4', '81', '55', '27', '18', '14', '23', '22', '2', '20', '3', '16', '77', '31', '11', '24', '63', '10']
core           INFO 	Loading data for Hungarian Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Successfully loaded British Grand Prix

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['81', '4', '44', '16', '1', '55', '11', '63', '22', '18', '14', '3', '27', '23', '20', '77', '2', '31', '24', '10']
core           INFO 	Loading data for Belgian Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Successfully loaded Hungarian Grand Prix

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Fixed incorrect tyre stint information for driver '14'
core        WARNING 	Fixed incorrect tyre stint information for driver '3'
core        WARNING 	Fixed incorrect tyre stint information for driver '18'
core        WARNING 	Fixed incorrect tyre stint information for driver '22'
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['44', '81', '16', '1', '4', '55', '11', '14', '31', '3', '18', '23', '10', '20', '77', '22', '2', '27', '24', '63']
core           INFO 	Loading data for Dutch Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Successfully loaded Belgian Grand Prix

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['4', '1', '16', '81', '55', '11', '63', '44', '10', '14', '27', '3', '18', '23', '31', '2', '22', '20', '77', '24']
core           INFO 	Loading data for Italian Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Successfully loaded Dutch Grand Prix

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['16', '81', '4', '55', '44', '1', '63', '11', '23', '20', '14', '43', '3', '31', '10', '77', '27', '24', '18', '22']
core           INFO 	Loading data for Azerbaijan Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Successfully loaded Italian Grand Prix

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['81', '16', '63', '4', '1', '14', '23', '43', '44', '50', '27', '10', '3', '24', '31', '77', '11', '55', '18', '22']
core           INFO 	Loading data for Singapore Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info
req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...

Successfully loaded Azerbaijan Grand Prix

req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['4', '1', '81', '63', '16', '44', '55', '14', '27', '11', '43', '22', '31', '18', '24', '77', '10', '3', '20', '23']
events      WARNING 	Correcting user input 'United States Grand Prix' to 'United States Grand Prix'
core           INFO 	Loading data for United States Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Successfully loaded Singapore Grand Prix

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['16', '55', '1', '4', '81', '63', '11', '27', '30', '43', '20', '10', '14', '22', '18', '23', '77', '31', '24', '44']
core           INFO 	Loading data for Mexico City Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Successfully loaded United States Grand Prix

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['55', '4', '16', '44', '63', '1', '20', '81', '27', '10', '18', '43', '31', '77', '24', '30', '11', '14', '23', '22']
core           INFO 	Loading data for São Paulo Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Successfully loaded Mexico City Grand Prix

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 23)
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 18)
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '31', '10', '63', '16', '4', '22', '81', '30', '44', '11', '50', '77', '14', '24', '55', '43', '23', '18', '27']
core           INFO 	Loading data for Las Vegas Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Successfully loaded São Paulo Grand Prix

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Driver 63: Lap timing integrity check failed for 2 lap(s)
core        WARNING 	Driver 44: Lap timing integrity check failed for 1 lap(s)
core        WARNING 	Driver 55: Lap timing integrity check failed for 1 lap(s)
core        WARNING 	Driver 16: Lap timing integrity check failed for 2 lap(s)
core        WARNING 	Driver  1: Lap timing integrity check failed for 1 lap(s)
core        WARNING 	Driver  4: Lap timing integrity check failed for 1 lap(s)
core        WARNING 	Driver 81: Lap timing integrity check failed for 1 lap(s)
core        WARNING 	Driver 30: Lap timing integrity check failed for 2 lap(s)
core        WARNING 	Driver 77: Lap timing integrity check failed for 2 lap(s)
core        WARNING 	Driver 63 completed the race distance 00:00.427000 before the recorded end of the session.
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['63', '44', '55', '16', '1', '4', '81', '27', '22', '11', '14', '20', '24', '43', '18', '30', '31', '77', '23', '10']
events      WARNING 	Correcting user input 'Qatar Grand Prix' to 'Qatar Grand Prix'
core           INFO 	Loading data for Qatar Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Successfully loaded Las Vegas Grand Prix

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
core        WARNING 	Fixed incorrect tyre stint information for driver '43'
core        WARNING 	Fixed incorrect tyre stint information for driver '31'
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['1', '16', '81', '63', '10', '55', '14', '24', '20', '4', '77', '44', '22', '30', '23', '27', '11', '18', '43', '31']
core           INFO 	Loading data for Abu Dhabi Grand Prix - Race [v3.8.3]
req            INFO 	Using cached data for session_info
req            INFO 	Using cached data for driver_info

Successfully loaded Qatar Grand Prix

req            INFO 	Using cached data for session_status_data
req            INFO 	Using cached data for lap_count
req            INFO 	Using cached data for track_status_data
req            INFO 	Using cached data for _extended_timing_data
req            INFO 	Using cached data for timing_app_data
core           INFO 	Processing timing data...
req            INFO 	Using cached data for car_data
req            INFO 	Using cached data for position_data
req            INFO 	Using cached data for weather_data
req            INFO 	Using cached data for race_control_messages
core           INFO 	Finished loading data for 20 drivers: ['4', '55', '16', '44', '63', '1', '10', '27', '14', '81', '23', '22', '24', '18', '61', '20', '30', '77', '43', '11']

Successfully loaded Abu Dhabi Grand Prix

In [6]:
# to avoid making features manually we can make a function for it

def add_features(df):
    df = df[df["Status"] == "Finished"].copy()

    df = df.sort_values(by=["Abbreviation", "Year", "RoundNumber"])

    df["PreviousPosition"] = (
        df.groupby("Abbreviation")["Position"]
        .shift(1)
    )

    df["Rolling3Average"] = (
        df.groupby("Abbreviation")["Position"]
        .rolling(window=3)
        .mean()
        .reset_index(0, drop=True)
    )

    df = df.dropna(subset=["PreviousPosition", "Rolling3Average"])

    return df

In [7]:
df_2023 = add_features(df_2023)
df_2024 = add_features(df_2024)

In [8]:
features = [
    "TeamName",
    "GridPosition",
    "PreviousPosition",
    "Rolling3Average",
    "Position"
]

train_df = df_2023[features]
test_df = df_2024[features]

In [9]:
df_2023["PositionChange"] = df_2023["GridPosition"] - df_2023["Position"]
df_2024["PositionChange"] = df_2024["GridPosition"] - df_2024["Position"]

C:\Users\Ashen\AppData\Local\Temp\ipykernel_5308\927599705.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_2023["PositionChange"] = df_2023["GridPosition"] - df_2023["Position"]

In [10]:
df_2023 = df_2023.sort_values(by=["Abbreviation", "RoundNumber"])
df_2024 = df_2024.sort_values(by=["Abbreviation", "RoundNumber"])

In [11]:
df_2023["AveragePositionChange"] = (
    df_2023.groupby("Abbreviation")["PositionChange"]
    .transform(lambda x: x.rolling(window=3).mean())
)

df_2024["AveragePositionChange"] = (
    df_2024.groupby("Abbreviation")["PositionChange"]
    .transform(lambda x: x.rolling(window=3).mean())
)

In [12]:
df_2023["AveragePositionChange"] = df_2023["AveragePositionChange"].fillna(0)
df_2024["AveragePositionChange"] = df_2024["AveragePositionChange"].fillna(0)

In [13]:
features = [
    "TeamName",
    "GridPosition",
    "PreviousPosition",
    "Rolling3Average",
    "AveragePositionChange",
    "Position"
]

train_df = df_2023[features]
test_df = df_2024[features]

In [14]:
combined_df = pd.concat([train_df, test_df], ignore_index=True)
# we combine all the data so we can encode everything at once

combined_df = pd.get_dummies(combined_df, columns=["TeamName"])

train_encoded = combined_df.iloc[:len(train_df)]
test_encoded = combined_df.iloc[len(train_df):]

In [15]:
# 2023 data
X_train = train_encoded.drop("Position", axis=1)
y_train = train_encoded["Position"]

# 2024 data
X_test = test_encoded.drop("Position", axis=1)
y_test = test_encoded["Position"]

# 2023 is what we are training and 2024 is what we want to test

# for safety we will also do a join

X_train, X_test = X_train.align(X_test, join="left", axis=1, fill_value=0)

In [16]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_errors

model = RandomForestRegressor(n_estimators=100, random_state=42)

model.fit(X_train, y_train)

RandomForestRegressor(random_state=42)

In [17]:
df_2023["Consistency"] = (
    df_2023.groupby("Abbreviation")["PositionChange"]
    .transform(lambda x: x.rolling(window=3).std())
)

df_2024["Consistency"] = (
    df_2024.groupby("Abbreviation")["PositionChange"]
    .transform(lambda x: x.rolling(window=3).std())
)

df_2023["Consistency"] = df_2023["Consistency"].fillna(0)
df_2024["Consistency"] = df_2024["Consistency"].fillna(0)

In [18]:
features = [
    "TeamName",
    "GridPosition",
    "PreviousPosition",
    "AveragePositionChange",
    "Consistency",
    "Position"
]

train_2023 = df_2023[features]
test_2024 = df_2024[features]

In [19]:
combined_df = pd.concat([train_df, test_df], ignore_index=True)
# we combine all the data so we can encode everything at once

combined_df = pd.get_dummies(combined_df, columns=["TeamName"])

train_encoded = combined_df.iloc[:len(train_df)]
test_encoded = combined_df.iloc[len(train_df):]

# 2023 data
X_train = train_encoded.drop("Position", axis=1)
y_train = train_encoded["Position"]

# 2024 data
X_test = test_encoded.drop("Position", axis=1)
y_test = test_encoded["Position"]

# 2023 is what we are training and 2024 is what we want to test

# for safety we will also do a join

X_train, X_test = X_train.align(X_test, join="left", axis=1, fill_value=0)

In [20]:
df_2023["GridvsForm"] = df_2023["GridPosition"] - df_2023["Rolling3Average"]
df_2024["GridvsForm"] = df_2024["GridPosition"] - df_2024["Rolling3Average"]
# since rolling 3 average is very dominating
# we can use that feature to make new features
# we can check the grid position against the form of the driver 
# this will let us see if the driver is overperforming or underperforming compared to their recent form

df_2023["FormTrend"] = df_2023["Rolling3Average"] - df_2023["PreviousPosition"]
df_2024["FormTrend"] = df_2024["Rolling3Average"] - df_2024["PreviousPosition"]

features = [
    "TeamName",
    "GridPosition",
    "PreviousPosition",
    "AveragePositionChange",
    "Consistency",
    "GridvsForm",
    "FormTrend",
    "Position"
]

train_2023 = df_2023[features].copy()
test_2024 = df_2024[features].copy()

combined_df = pd.concat([train_2023, test_2024], ignore_index=True)
combined_df = pd.get_dummies(combined_df, columns=["TeamName"])

train_encoded = combined_df.iloc[:len(train_2023)]
test_encoded = combined_df.iloc[len(train_2023):]

X_train = train_encoded.drop("Position", axis=1)
y_train = train_encoded["Position"]

X_test = test_encoded.drop("Position", axis=1)
y_test = test_encoded["Position"]

print("Rolling3Average" in X_train.columns)
print(X_train.columns)

False
Index(['GridPosition', 'PreviousPosition', 'AveragePositionChange',
       'Consistency', 'GridvsForm', 'FormTrend', 'TeamName_Alfa Romeo',
       'TeamName_AlphaTauri', 'TeamName_Alpine', 'TeamName_Aston Martin',
       'TeamName_Ferrari', 'TeamName_Haas F1 Team', 'TeamName_Kick Sauber',
       'TeamName_McLaren', 'TeamName_Mercedes', 'TeamName_RB',
       'TeamName_Red Bull Racing', 'TeamName_Williams'],
      dtype='object')

In [21]:
model = RandomForestRegressor(n_estimators=100, random_state=42)

model.fit(X_train, y_train)

prediction = model.predict(X_test)

mean_error = mean_absolute_error(y_test, prediction)
print(f"Mean Absolute Error: {mean_error:.2f}")

# HERE WE REMOVED THE ROLLING 3 AVERAGE FEATURE
# BECAUSE THAT FEATURE BASICALLY DOMINATED THE ENTIRE MODEL
# NOW THE ERROR HAS INCREASED BUT WE CAN SEE OTHER FEATURES HAVE MORE IMPORTANCE NOW

Mean Absolute Error: 1.49

In [22]:
comparison = pd.DataFrame({
    "Actual": y_test,
    "Predicted": prediction
})

print(comparison.head(20))

     Actual  Predicted
277    18.0  13.586667
278     9.0   9.460000
279    12.0  13.280000
280     9.0   8.075000
281     7.0  10.360000
282     8.0   7.820000
283     6.0   5.260000
284     7.0   6.190000
285     9.0   9.650000
286     6.0   7.130000
287     8.0   8.020000
288    11.0   8.090000
289     8.0   7.180000
290    11.0  10.360000
291     6.0   6.590000
292    14.0   9.300000
293    11.0   9.430000
294     7.0  12.150000
295     9.0   8.770000
296    12.0  11.800000

In [ ]:
comparison = test_df.copy()

comparison["Actual"] = y_test.values
comparison["Predicted"] = prediction
comparison["PredictedRounded"] = comparison["Predicted"].round().astype(int)
comparison["Error"] = (comparison["Actual"] - comparison["Predicted"]).abs()
# error is how far off the prediction is from the actual position

comparison = comparison.sort_values(by="Predicted")

comparison.head(20)

# we can see that the model is doing a decent job at predicting the positions
# however once in a while it makes some big errors

,TeamName,GridPosition,PreviousPosition,Rolling3Average,AveragePositionChange,Position,Actual,Predicted,PredictedRounded,Error
79,Red Bull Racing,1.0,1.0,1.000000,0.000000,1.0,1.0,1.00,1,0.00
99,Red Bull Racing,1.0,1.0,1.000000,0.000000,1.0,1.0,1.00,1,0.00
139,Red Bull Racing,1.0,2.0,1.333333,-0.333333,1.0,1.0,1.04,1,0.04
40,Red Bull Racing,1.0,1.0,1.333333,0.000000,1.0,1.0,1.05,1,0.05
120,Red Bull Racing,1.0,1.0,1.333333,-0.333333,2.0,2.0,1.07,1,0.93
80,Red Bull Racing,2.0,5.0,3.000000,0.000000,2.0,2.0,1.53,2,0.47
199,Red Bull Racing,2.0,1.0,2.666667,0.666667,1.0,1.0,1.56,2,0.56
101,Red Bull Racing,2.0,2.0,3.333333,0.000000,3.0,3.0,1.58,2,1.42
381,Red Bull Racing,2.0,2.0,3.333333,0.000000,3.0,3.0,1.58,2,1.42
223,Red Bull Racing,1.0,1.0,2.333333,-0.666667,5.0,5.0,1.66,2,3.34
300,Red Bull Racing,2.0,4.0,3.666667,1.666667,2.0,2.0,1.70,2,0.30
360,Red Bull Racing,2.0,5.0,4.333333,0.666667,2.0,2.0,1.74,2,0.26
404,Red Bull Racing,2.0,3.0,3.666667,-1.666667,6.0,6.0,1.76,2,4.24
200,McLaren,1.0,2.0,2.666667,0.000000,2.0,2.0,1.80,2,0.20
260,McLaren,1.0,3.0,2.333333,-0.666667,2.0,2.0,1.85,2,0.15
159,Ferrari,1.0,3.0,2.333333,-0.333333,1.0,1.0,1.86,2,0.86
179,Red Bull Racing,2.0,6.0,2.666667,0.333333,1.0,1.0,1.89,2,0.89
140,McLaren,2.0,1.0,1.666667,2.000000,2.0,2.0,2.08,2,0.08
339,McLaren,2.0,2.0,2.333333,0.000000,1.0,1.0,2.11,2,1.11
459,Red Bull Racing,2.0,5.0,2.333333,5.666667,1.0,1.0,2.12,2,1.12

In [26]:
test_info = df_2024[["Abbreviation", "TeamName", "RaceName", "RoundNumber", "Position"]].copy()

print(df_2024.columns)

Index(['Abbreviation', 'TeamName', 'GridPosition', 'Position', 'Status',
       'RaceName', 'RoundNumber', 'Year', 'PreviousPosition',
       'Rolling3Average', 'PositionChange', 'AveragePositionChange',
       'Consistency', 'GridvsForm', 'FormTrend'],
      dtype='object')

In [ ]:
fantasy_table = test_info.copy()

fantasy_table["Predicted"] = prediction
fantasy_table["PredictedRounded"] = fantasy_table["Predicted"].round().astype(int)
# forgot to explain earlier, here we round up the predicted position
# because value we get is a continuous value and we want to convert it to a discrete position

fantasy_table["Error"] = (fantasy_table["Position"] - fantasy_table["Predicted"]).abs()

fantasy_table = fantasy_table.sort_values(by="Predicted")

fantasy_table.head(20)

# this table is what we will use for the fantasy predictor

,Abbreviation,TeamName,RaceName,RoundNumber,Position,Predicted,PredictedRounded,Error
79,VER,Red Bull Racing,Japanese Grand Prix,4,1.0,1.00,1,0.00
99,VER,Red Bull Racing,Chinese Grand Prix,5,1.0,1.00,1,0.00
139,VER,Red Bull Racing,Emilia Romagna Grand Prix,7,1.0,1.04,1,0.04
40,VER,Red Bull Racing,Saudi Arabian Grand Prix,2,1.0,1.05,1,0.05
120,VER,Red Bull Racing,Miami Grand Prix,6,2.0,1.07,1,0.93
80,PER,Red Bull Racing,Japanese Grand Prix,4,2.0,1.53,2,0.47
199,VER,Red Bull Racing,Spanish Grand Prix,10,1.0,1.56,2,0.56
101,PER,Red Bull Racing,Chinese Grand Prix,5,3.0,1.58,2,1.42
381,VER,Red Bull Racing,United States Grand Prix,19,3.0,1.58,2,1.42
223,VER,Red Bull Racing,Austrian Grand Prix,11,5.0,1.66,2,3.34
300,VER,Red Bull Racing,Dutch Grand Prix,15,2.0,1.70,2,0.30
360,VER,Red Bull Racing,Singapore Grand Prix,18,2.0,1.74,2,0.26
404,VER,Red Bull Racing,Mexico City Grand Prix,20,6.0,1.76,2,4.24
200,NOR,McLaren,Spanish Grand Prix,10,2.0,1.80,2,0.20
260,NOR,McLaren,Hungarian Grand Prix,13,2.0,1.85,2,0.15
159,LEC,Ferrari,Monaco Grand Prix,8,1.0,1.86,2,0.86
179,VER,Red Bull Racing,Canadian Grand Prix,9,1.0,1.89,2,0.89
140,NOR,McLaren,Emilia Romagna Grand Prix,7,2.0,2.08,2,0.08
339,PIA,McLaren,Azerbaijan Grand Prix,17,1.0,2.11,2,1.11
459,VER,Red Bull Racing,Qatar Grand Prix,23,1.0,2.12,2,1.12

In [ ]:
# Now we try something different
# We try to pick a race and then see what the predictions are

race_name = "Japanese Grand Prix"

race_predictions = fantasy_table[
    fantasy_table["RaceName"] == race_name
].sort_values(by="Position")

race_predictions.head(20)

# Here we provide the race name and use the fantasy table to see the predictions
# And then we sort by the position cuz i believe its easier
# And there is pretty good correlation between the predicted and actual positions

,Abbreviation,TeamName,RaceName,RoundNumber,Position,Predicted,PredictedRounded,Error
79,VER,Red Bull Racing,Japanese Grand Prix,4,1.0,1.00,1,0.00
80,PER,Red Bull Racing,Japanese Grand Prix,4,2.0,1.53,2,0.47
81,SAI,Ferrari,Japanese Grand Prix,4,3.0,5.40,5,2.40
82,LEC,Ferrari,Japanese Grand Prix,4,4.0,5.17,5,1.17
83,NOR,McLaren,Japanese Grand Prix,4,5.0,3.73,4,1.27
84,ALO,Aston Martin,Japanese Grand Prix,4,6.0,5.26,5,0.74
85,RUS,Mercedes,Japanese Grand Prix,4,7.0,6.51,7,0.49
86,PIA,McLaren,Japanese Grand Prix,4,8.0,5.64,6,2.36
87,HAM,Mercedes,Japanese Grand Prix,4,9.0,9.57,10,0.57